apis-is/apis

endpoints/tv/index.js
Adds array of objects containing Icelandic TV channel names along with their endpoints. Backwards compatible and non breaking change that helps you build an application without updating the routes for channels
=> Default reponse change for /tv

.travis.yml
Hopefully this will fix the errors on travis. Making a PR to test before merging.
=> Fix tests for 0.8 on travis.

endpoints/company/tests/integration_test.js, endpoints/hospital/tests/integration_test.js, endpoints/sports/tests/integration_test.js, endpoints/weather/tests/integration_test.js, test/integration/endpoints.js
Just trying things out. Maybe we can see something green in this.
=> Skip both sports endpoints in tests.

README.md
Replaces #165 since it got messed up.
=> Add some cool guys as maintainers.

endpoints/firm/docs.json
=> Create a docs.json for /firm endpoint

.gitignore, .jshintignore, .jshintrc, .travis.yml, package.json
=> Add JSHinting to travis.

package.json, src/endpoints/vinbud/docs.json, src/endpoints/vinbud/index.js, src/endpoints/vinbud/test.js
I abstracted the fetching of data into a separate module and here it is. Still getting a weird error on the test tho.
```
1) /vinbud Searching should succeed:
Error: expected "Content-Type" matching /json/, got "text/html; charset=utf-8"
at Test.assert (/Users/koddsson/Repos/apis/node_modules/supertest/lib/test.js:196:25)
at Server.assert (/Users/koddsson/Repos/apis/node_modules/supertest/lib/test.js:132:12)
at Server.g (events.js:199:16)
at Server.emit (events.js:104:17)
at net.js:1392:10
at process._tickDomainCallback (node.js:381:11)
```
=> Add /vinbud/ endpoint.

index.js, test.js
This is for the new `docs.beta.apis.is`.
=> Added `/docs.json` to return the documentation of every endpoint

endpoints/firm/docs.json
=> Fix firm/docs.json

README.md
=> Updated codeship status image in README.md

.jshintignore
Add `coverage/` folder to `.jshintignorerc`. :tophat:
=> Add coverage/ to jshint ignore.

endpoints/firm/test.js, index.js, test.js
Add test and removed unnecessary code.
=> Up the code coverage.

endpoints/tvinna/docs.json, endpoints/tvinna/index.js, endpoints/tvinna/test.js, package.json
Parsing [tvinna.is](tvinna.is) for cool jobs!
=> Add /tvinna/ endpoint!

endpoints/car/docs.json, endpoints/car/index.js, endpoints/car/test.js, package.json
NOTE! @kristjanmik must merge [this](https://github.com/kristjanmik/car/pull/1) first, do a version bump + npm publish, then merge this and update package.json with latest car package (jeijj)
=> Create car endpoint - using npm package 'car'

endpoints/althingi/docs.json, endpoints/althingi/index.js, endpoints/althingi/test.js, package.json
I think this is interesting data to a lot of people. @jamesrobb being one of those people ;)
=> Add a althingi scraper and endpoint.

endpoints/jobs/docs.json, endpoints/jobs/index.js, endpoints/jobs/test.js
Just a thought! Applying the same logic as with /firm/is for icelandic companies
=> Rename /tvinna to /jobs/tvinna, allowing for more future job listings

endpoints/cinema/index.js, endpoints/particulates/index.js, endpoints/particulates/tests/integration_test.js, package.json
The tests are failing on codeship. This should fix that.
=> Fix some cinema tests for the build.

endpoints/hljomaholl/index.js
The endpoint was not pulling correct date and time for events, now fixed and verified.
Fixed also double slash in 'moreInfoURL'
=> endpoint /hljomaholl now retreives correct date and time

package.json, test/integration/endpoints.js
Was unable to run `npm test` on windows.
=> Fix tests on Windows

endpoints/sports/index.js, endpoints/sports/tests/integration_test.js
Now apis provides an api to the top football leagues in Icelandic football.
=> added some leagues to the sports/football api

endpoints/vinbud/docs.json, endpoints/vinbud/index.js, endpoints/vinbud/test.js, package.json
Thanks to @davidarnarsson and his wonderful [scraper](https://github.com/davidarnarsson/vinbud-scraper) we are in the business of all items offered in the liquor store.
=> Add new `vinbud` version that includes items

endpoints/hljomaholl/index.js, endpoints/hljomaholl/tests/integration_test.js
This is mostly just style fixes. The real fix was adding a `true` value for the `canBeEmpty` variable in the test helper class. It's isolated in commit 02896d4 if you wanna take a look.
=> Fix hljomaholl endpoint.

.travis.yml
I'm testing the travis file. Don't mind me.
=> Clean up the travis file

endpoints/names/index.js
Tests have been failing for a few days. Decided to take a look. Basic fix.
=> island.is changed url format used for /names

Makefile, endpoints/bus/realtime.js, endpoints/golf/index.js, endpoints/tv/skjarinn.js, endpoints/tv/tests/integration_test.js, lib/redis.js, package.json
=> Some cleanup

endpoints/cinema/index.js
For the tests to work for this pull request #246 has to be merged because of the ES2015 syntax
=> Fixed and rewrote /cinema with ES2015

package.json, server.js
We have to have some global error handler. Having one is very useful for using the next next function in endpoints.
=> Some global error handling

endpoints/company/index.js
Example of what i got before the changes: Kaffikl&#xFA;bburinn ehf
Now: Kaffiklúbburinn ehf
=> Set decodeEntities to false to prevent a html encoded string

endpoints/tv/skjarinn.js
This has been causing us pain in production
=> Make sure we dont continue because shit hits the fan

endpoints/lottery/index.js, endpoints/tv/365.js, endpoints/tv/ruv.js
Removed a lot of `throw`s in async code
=> Less throwing

.travis.yml
=> travis: Added node 5

endpoints/horses/tests/integration_test.js
This test was failing on master randomly.
=> Up the timeout for a flaky /horses test

.github/ISSUE_TEMPLATE, .github/PULL_REQUEST_TEMPLATE
A initial commit for issue and PR templates. I deliberately didn't put too much info in there. Figured it would be good to start small and see how people react and use these before adding more. 
cc/ @benediktvaldez @MiniGod @kristjanmik 
Fixes #254
=> Initial issue and PR templates

endpoints/horses/index.js
My assumptions in https://github.com/apis-is/apis/pull/273 that we would get like max 8 horses in multi-responses were terribly wrong!!
Check out the below link, then merge this asap, and afterwards scream if you need to.
http://www.worldfengur.com/freezone_horse.jsp?c=EN&fnr=&nafn=a&uppruni=a&ormerkja=&leitahnappur=Search+&leita=1
=> Do NOT do individual requests for multi-result data if horses not less than 8!

endpoints/horses/index.js
See https://github.com/apis-is/apis/pull/279
=> fixing lint issues from my last PR

endpoints/isnic/index.js, endpoints/isnic/tests/integration_test.js
New endpoint, it's a simple scraper of isnic whois loopup: https://www.isnic.is/is/whois/search
Copy of car endpoint, very simple scraper endpoint.
=> Added isnic endpoint

endpoints/petrol/index.js, endpoints/petrol/tests/integration_test.js
New endpoint, providing list of all petrol stations in Iceland, including geo location and gas prices, provided by the open gasvaktin project on github.
Gasvaktin scrapes prices for bensin and diesel from all the oil companies web sites every 15 minutes and auto commits to the github.com/gasvaktin/gasvaktin repo in case of changes. Also provides default discount price for bensin and diesel for each station which can be obtained by anyone by applying for gas key or card or registering to some program.
Will open another pull request for documentation as it's on another branch.
=> Added petrol stations endpoint

index.html
Added docs for new endpoint petrol stations.
See: https://github.com/apis-is/apis/pull/290
=> Added docs for new endpoint petrol stations

endpoints/calendar/index.js, endpoints/calendar/tests/integration_test.js, package.json
People have been requesting a endpoint for icelandic holidays and this is it!
Closes #272
=> Add calendar endpoint

endpoints/currency/arion.js
beginDate was set to Yesterday. Correct date is today
=> Currency endpoint: Wrong date in beginDate parameter in arion.js

endpoints/cinema/index.js, endpoints/cinema/tests/integration_test.js
=> Fix DOM selecting in `/cinema` endpoint

index.html
See [pull request #365](https://github.com/apis-is/apis/pull/365).
=> Documentation for auroracoin endpoint

index.html
Documentation for Icelandic Ship Registry endpoint added in #372
=> Added /ship endpoint documentation

package-lock.json, package.json
=> chore(package): update sinon to version 4.1.1

package.json
=> chore(package): update nodemon to version 1.12.7

endpoints/hospital/tests/integration_test.js, package-lock.json, package.json
=> fix(package): update expect to version 22.0.3

package-lock.json, package.json
=> fix(package): update moment to version 2.20.1

package-lock.json, package.json
=> fix(package): update graphql to version 0.12.3

package.json
=> fix(package): update iconv-lite to version 0.4.21

package.json
=> fix(package): update mocha to version 5.1.1

endpoints/address/graphql_schema.js, endpoints/address/index.js, endpoints/bus/graphql_schema.js, endpoints/calendar/graphql_schema.js, endpoints/calendar/index.js, endpoints/calendar/tests/integration_test.js, endpoints/car/graphql_schema.js, endpoints/car/index.js, endpoints/earthquake/index.js, endpoints/ship/index.js, lib/cache.js, make-docs.js, package-lock.json, package.json
I'm trusting the tests on this one...
Closes #450 Closes #435
=> style: update xo to latest

server.js
=> Prevent sentry/raven install when dns is missing
